version: "2"

run:
  timeout: 5m
  go: "1.26.2"
  modules-download-mode: vendor

linters:
  default: none
  enable:
    - gosec
    - govet
    - revive
    - unused
  exclusions:
    rules:
      - path: _test\.go
        linters:
          - gosec
      - path: ^tests/
        linters:
          - gosec
    paths:
      - third_party/
      - builtin/
      - examples/
  settings:
    revive:
      rules:
        - name: exported
          disabled: true
        - name: package-comments
          disabled: true
