timeout: 9000s
options:
  substitution_option: ALLOW_LOOSE
steps:
  # v20260205-38cfa9523f (digest-pinned; see kubernetes/kubernetes#138936)
  - name: 'gcr.io/k8s-staging-test-infra/gcb-docker-gcloud@sha256:ff388e0dc16351e96f8464e2e185b74a7578a5ccb7a112cf3393468e59e6e2d2'
    entrypoint: bash
    env:
    - TAG=$_GIT_TAG
    - BASE_REF=$_PULL_BASE_REF
    - DOCKER_CLI_EXPERIMENTAL=enabled
    # default cloudbuild has HOME=/builder/home and docker buildx is in /root/.docker/cli-plugins/docker-buildx
    # set the home to /root explicitly to if using docker buildx
    - HOME=/root
    args:
      - '-c'
      - |
        gcloud auth configure-docker \
        && make release-staging
substitutions:
  # _GIT_TAG will be filled with a git-based tag for the image, of the form vYYYYMMDD-hash, and
  # can be used as a substitution
  _GIT_TAG: '12345'
  _PULL_BASE_REF: 'dev'
